### ISSUE TITLE
Error in Typescript build 

### ISSUE THREAD

**Issue by mayankcertree** [shamscorner/vue-3-stackter#3]
Any idea to resolve this
![image](https://user-images.githubusercontent.com/71604065/144563292-68b5155d-09f8-4bae-85a1-3670ea487f47.png)

**Comment by shamscorner** [comment]
I will recommend you not to use the Typescript version...because I am gonna change many of the settings there especially vuex -> pinia and also some other typing-related issues. 

But if you want to try (vite + vue 3 + typescript) in your project, I will highly recommend you to use [vitesse](https://github.com/antfu/vitesse) or if you want a forked version of this with a clean and modular architecture pattern, then go for one of my repo here [vitesse-stackter-clean-architect](https://github.com/shamscorner/vitesse-stackter-clean-architect)

**Comment by mayankcertree** [comment]
Thank you for prompt response. will give it a try.
